all:
	g++ -std=gnu++11 main.cpp generadorRectas.cpp matrix.cpp ppmloader.cpp aplicadorRectas.cpp -Wall -ggdb -O0 -o tp3
test:
	g++ -std=gnu++11 tests.cpp generadorRectas.cpp matrix.cpp ppmloader.cpp aplicadorRectas.cpp -ggdb -o test
clean:
	rm -f tp3 test
