all:
	g++ -std=gnu++11 main.cpp generadorRectas.cpp matrix.cpp ppmloader.cpp aplicadorRectas.cpp -Wall -ggdb -O3 -o tp3
test:
	g++ -std=gnu++11 tests.cpp generadorRectas.cpp matrix.cpp ppmloader.cpp aplicadorRectas.cpp -Wall -ggdb -o test
csv:
	g++ -std=gnu++11 maincsv.cpp generadorRectas.cpp matrix.cpp ppmloader.cpp aplicadorRectas.cpp -Wall -ggdb -O3 -o csv
clean:
	rm -f tp3 test
